Add glusterfs-libs change to libglusterfs0 in relnotes
gluster/glusterdocs pull request #690
Opened 2021-07-20 07:50 UTC by bluikko

For https://github.com/gluster/glusterfs/issues/2231: mention in "Features" section that the `glusterfs-libs` RPM package is replaced with `libglusterfs0`.

2021-07-27 16:46 UTC, kshithijiyer approved these changes

2021-07-28 01:24 UTC, bluikko commented
Finally ran this update myself and saw that there are actually several `lib[...]` packages: `libgfxdr0`, `libgfrpc0`, `libgfapi0`, `libgfchangelog0` etc. - I wonder if this should be mentioned in the doc too?
```
The RPM package `glusterfs-libs` is replaced by `libglusterfs0` and other library packages.
```
Or something similar?

2021-08-11 04:32 UTC, Sheetalpamecha requested changes
Yes it would be better to mention it. For list of package you can check here -https://download.gluster.org/pub/gluster/glusterfs/8/8.5/Debian/10/amd64/apt/pool/main/g/glusterfs/

2021-08-11 04:53 UTC, bluikko commented
I have added all the 6 library packages, and mention the 4 that replace `glusterfs-libs` from the other 2. Would you need me to squash the commits or will you squash on merge?

2021-08-11 05:17 UTC, Sheetalpamecha commented
> I have added all the 6 library packages, and mention the 4 that replace `glusterfs-libs` separately from the other 2. Would you need me to squash the commits or will you squash on merge?

I will squash on merging

2021-08-11 05:17 UTC, Sheetalpamecha approved these changes

2021-08-11 05:19 UTC, merged