[Install-Guide] Fixes and improvements
gluster/glusterdocs pull request #736
Opened 2022-05-19 07:52 UTC by black-dragon74

Also, cleaned up the syntax.

Signed-off-by: black.dragon74 <nickk.2974@gmail.com>

2022-05-19 07:56 UTC, black-dragon74 commented
Reviewer's Note: This patch also hides copy code button on the last code block in `Configure.md`. That feature depends on #732 so it will be effective once that is merged.

The annotation used to hide that button is backwards compatible and won't break any syntax highlighting/formatting on the code block.

Regards

2022-05-19 07:56 UTC, black-dragon74 commented
CC: @Shwetha-Acharya

2022-06-13 06:31 UTC, Sheetalpamecha requested changes

2022-06-13 06:31 UTC, Sheetalpamecha commented on docs/Install-Guide/Configure.md
> +but hasn’t yet been started, which would cause any attempt to mount the volume fail.
The above code and this para is not correctly formatted. You might want to recheck it.

2022-06-13 06:31 UTC, Sheetalpamecha commented on docs/Install-Guide/Configure.md
> +gluster volume start gv0
Should be ```console in line 124

2022-07-01 07:24 UTC, rakshithakamath94 approved these changes

2022-07-01 07:25 UTC, merged