[cli-ref] Fix table spacing and better syntax
gluster/glusterdocs pull request #738
Opened 2022-05-30 06:41 UTC by black-dragon74

Signed-off-by: black-dragon74 <niryadav@redhat.com>

2022-05-30 07:43 UTC, kshithijiyer approved these changes
LGTM

2022-05-31 11:43 UTC, Shwetha-Acharya requested changes

2022-05-31 11:43 UTC, Shwetha-Acharya commented on docs/CLI-Reference/cli-main.md
> +| Command              | Syntax                                                                             | Description
Please refer https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables 

Previous changes work equally good.

2022-05-31 11:55 UTC, black-dragon74 commented on docs/CLI-Reference/cli-main.md
> +| Command              | Syntax                                                                             | Description
Done.

2022-05-31 12:01 UTC, merged